// Generated by https://quicktype.io

export interface Hero {
    id:         string;
    name:       string;
    lastname:   Lastname;
    user:       string;
    password:   string;
    characters: string;
}

export enum Lastname {
    DCComics = "DC Comics",
    MarvelComics = "Mar vel Comics",
}
